#!/usr/bin/env bash

# We no longer have '\n' as delimiter, changed it to empty string (end of null-byte)
# BUT: Everything after '|' is executed within a subshell - so i still equals 0 when we turn back.
i=0
find ./files -type f -print0 | while read -r -d '' file; do
	echo "<$file>"
	((i++))
done
echo "found $i files"
